//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crm_dev_dbEntities1 : DbContext
    {
        public crm_dev_dbEntities1()
            : base("name=crm_dev_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_CompanyDetail> tbl_CompanyDetail { get; set; }
        public virtual DbSet<tbl_CompanyShare> tbl_CompanyShare { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_IndividualDetail> tbl_IndividualDetail { get; set; }
        public virtual DbSet<tbl_Province> tbl_Province { get; set; }
        public virtual DbSet<tbl_Status> tbl_Status { get; set; }
        public virtual DbSet<tbl_TrustDetail> tbl_TrustDetail { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserAddressDetail> tbl_UserAddressDetail { get; set; }
        public virtual DbSet<tbl_UserBankDetail> tbl_UserBankDetail { get; set; }
        public virtual DbSet<tbl_UserMasterDetail> tbl_UserMasterDetail { get; set; }
    }
}
