//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public tbl_User()
        {
            this.tbl_UserMasterDetail = new HashSet<tbl_UserMasterDetail>();
        }
    
        public int UserID { get; set; }
        public string PWD { get; set; }
        public string Mobile { get; set; }
        public string EmailID { get; set; }
        public string TrustRegistrationID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] DeleteFlag { get; set; }
    
        public virtual ICollection<tbl_UserMasterDetail> tbl_UserMasterDetail { get; set; }
    }
}
