//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserMasterDetail
    {
        public int UserMasterDetailID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SpouseID { get; set; }
        public string ChildrenID1 { get; set; }
        public string ChildrenID2 { get; set; }
        public string ChildrenID3 { get; set; }
        public string ChildrenID4 { get; set; }
        public string ChildrenID5 { get; set; }
        public string TrustID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual tbl_TrustDetail tbl_TrustDetail { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
