//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trust
    {
        public int TrustID { get; set; }
        public string UIC { get; set; }
        public string TrustName { get; set; }
        public Nullable<System.DateTime> YearOfFoundation { get; set; }
        public string Telephone { get; set; }
        public string FaxNo { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string TaxRefNo { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> AdvisorID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
