//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AddressDetail
    {
        public int AddressDetailID { get; set; }
        public Nullable<int> Type { get; set; }
        public string SAID { get; set; }
        public string ReferenceSAID { get; set; }
        public string UIC { get; set; }
        public string HouseNo { get; set; }
        public string BuildingName { get; set; }
        public string Floor { get; set; }
        public string FlatNo { get; set; }
        public string RoadName { get; set; }
        public string RoadNo { get; set; }
        public string SuburbName { get; set; }
        public Nullable<int> City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
