//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserBankDetail
    {
        public int UserBankDetailID { get; set; }
        public Nullable<int> SAID { get; set; }
        public string Type { get; set; }
        public string TAXreference { get; set; }
        public string BankName { get; set; }
        public Nullable<int> BranchNumber { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string Currency { get; set; }
        public string SWIFT { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] DeleteFlag { get; set; }
    }
}
