//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClientServiceMaster
    {
        public int ClientServiceID { get; set; }
        public string SAID { get; set; }
        public Nullable<int> ClientService { get; set; }
        public string DetailInformation { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
