//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClientReg
    {
        public int ClientID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SAId { get; set; }
        public string Company { get; set; }
        public string CompanyRegNo { get; set; }
        public string Trust { get; set; }
        public string TrustRegNo { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedThrough { get; set; }
        public string ClientFeedback { get; set; }
        public string AdvisorFeedback { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
    }
}
