//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FeedBack
    {
        public int FeedBackID { get; set; }
        public Nullable<int> AdvisorID { get; set; }
        public string ClientSAID { get; set; }
        public string ClientFeedBack { get; set; }
        public string AdvisorFeedBack { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
