//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankDetail
    {
        public int BankDetailID { get; set; }
        public Nullable<int> Type { get; set; }
        public string SAID { get; set; }
        public string ReferenceID { get; set; }
        public string UIC { get; set; }
        public string BankName { get; set; }
        public string BranchNumber { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string Currency { get; set; }
        public string SWIFT { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
