//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanyDetail
    {
        public tbl_CompanyDetail()
        {
            this.tbl_CompanyShare = new HashSet<tbl_CompanyShare>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Year { get; set; }
        public string PlotNO { get; set; }
        public string BuildingName { get; set; }
        public string Floor { get; set; }
        public string FlatNo { get; set; }
        public string RoadName { get; set; }
        public string RoadNo { get; set; }
        public string SuburbName { get; set; }
        public Nullable<int> City { get; set; }
        public byte[] PostalCode { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> Country { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string IDPaths { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] DeleteFlag { get; set; }
    
        public virtual ICollection<tbl_CompanyShare> tbl_CompanyShare { get; set; }
    }
}
