//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAddressDetail
    {
        public int UserAddressDetailID { get; set; }
        public Nullable<int> SAID { get; set; }
        public string Type { get; set; }
        public string HouseNo { get; set; }
        public string BuildingName { get; set; }
        public string Floor { get; set; }
        public string Flat { get; set; }
        public string RoadName { get; set; }
        public string RoadNo { get; set; }
        public string SuburbName { get; set; }
        public Nullable<int> City { get; set; }
        public byte[] PostalCode { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] DeleteFlag { get; set; }
    }
}
